### ISSUE TITLE
Necessidade do `encode()` antes de chamar o aioamqp

### ISSUE THREAD

**Issue by daltonmatos** [B2W-BIT/easyqueue#11]
Hoje tentei processar um payload e o problema do unexpected frame ainda acontece.
```
$ time pipenv run python fluentd-chunk.py buffer.q5720edd59f802c3589fdaa46d9ad7806.log
Server closed connection: UNEXPECTED_FRAME - expected content body, got non content body frame instead, code=505, class_id=60, method_id=40
Connection lost exc=None
Traceback (most recent call last):
  File "fluentd-chunk.py", line 52, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "fluentd-chunk.py", line 50, in main
    raise e
  File "fluentd-chunk.py", line 45, in main
    await queue.put(body=event, routing_key=key, exchange="fluentd-logs")
  File "/home/daltonmatos/.local/share/virtualenvs/daltonmatos-3zssQDdZ/lib/python3.6/site-packages/easyqueue/async.py", line 94, in put
    routing_key=routing_key)
  File "/home/daltonmatos/.local/share/virtualenvs/daltonmatos-3zssQDdZ/lib/python3.6/site-packages/aioamqp/channel.py", line 804, in publish
    yield from self._write_frame(method_frame, method_request, drain=False)
  File "/home/daltonmatos/.local/share/virtualenvs/daltonmatos-3zssQDdZ/lib/python3.6/site-packages/aioamqp/channel.py", line 111, in _write_frame
    yield from self.protocol.ensure_open()
  File "/home/daltonmatos/.local/share/virtualenvs/daltonmatos-3zssQDdZ/lib/python3.6/site-packages/aioamqp/protocol.py", line 138, in ensure_open
    raise exceptions.AmqpClosedConnection()
aioamqp.exceptions.AmqpClosedConnection
```

Revertendo o commit 43fc58a6fc6cf03844012559d6a7e3ea10bfd7a4 o problema some e o consigo processar todas as mensagens.

```
$ time pipenv run python fluentd-chunk.py buffer.q5720edd59f802c3589fdaa46d9ad7806.log
Total de eventos: 165387
defaultdict(<class 'int'>,
            {'asgard.app.infra.asgard.api': 759,
             'asgard.app.infra.asgard.app-stats-collector': 379,
             'asgard.app.infra.asgard.logs.app-log-ingestor': 51,
             'asgard.app.infra.asgard.logs.app-stats-indexer': 4,
             'asgard.app.infra.asgard.logs.counts': 6,
             'asgard.app.sieve.captura.seller.calculator': 162998,
             'asgard.app.sieve.captura.seller.feed-buybox.buybox-stream-reader': 1171,
             'counts.errors.1m': 1,
             'counts.ok.1m': 8,
             'errors.asgard.app.infra.elk.es': 3,
             'fluent.info': 4,
             'fluent.warn': 3})
pipenv run python fluentd-chunk.py   12,46s user 0,63s system 85% cpu 15,255 total
```

O que acha de revertemos esse commit? @diogommartins @dnp1 

#6

**Comment by diogommartins** [comment]
Concordo. Abri um PR e marquei você como avaliador

**Comment by daltonmatos** [comment]
ok, já dei aprove lá. Acho que podemos mergear e fazer uma nova release. O que acha?

**Comment by diogommartins** [comment]
Foi mal te deixar no vácuo. Já tinha que ter saído isso a muito tempo ._.
